repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: go-fmt
        name: Go formatter
        language: system
        entry: go fmt ./...
        pass_filenames: false

  - repo: local
    hooks:
      - id: go-vet
        name: Go static analyzer
        language: system
        entry: go vet ./...
        pass_filenames: false

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint
        args: [--timeout=5m]
