#!/bin/sh

set -eu

build() {
    arch="${1}"
    GOOS=linux GOARCH="${arch}" ./make
}

build_android_arm64() {
    CGO_ENABLED=1 \
    GOOS="android" \
    GOARCH="arm64" \
    CC="aarch64-linux-android21-clang" \
    ./make
}

pack() {
    arch="${1}"
    tar -C bin/ -czf "t_$(git describe --tags --abbrev=0)_linux_${arch}.tar.gz" t
}

build_and_pack() {
    arch="${1}"
    build "${arch}"
    pack "${arch}"
}

build_and_pack_android() {
    build_android_arm64
    tar -C bin/ -czf "t_$(git describe --tags --abbrev=0)_android_arm64.tar.gz" t
}

build_and_pack "arm64"
build_and_pack "amd64"

build_and_pack_android
