#!/bin/sh

set -e

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
    if [ "$(cat VERSION)" != "$(git show HEAD:VERSION)" ]; then
        rootdir="$(git rev-parse --show-toplevel)"

        cd "${rootdir}"
        git add $(go generate ./...)
        sed "s/%VERSION%/v$(cat VERSION)/g" ./.release/README.md.template > README.md
        git add README.md
        git add $(go fmt ./...)

        export PATH="${PATH}:${HOME}/.local/opt/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin"
        "${rootdir}/gen_packages.sh"
    fi
fi

